#!/bin/bash

[ $# -lt 1 ] && echo "Need file" && exit 1

sum=0
while read line
do
  #echo $line
  a=$(echo $line | cut -d"x" -f1)
  b=$(echo $line | cut -d"x" -f2)
  c=$(echo $line | cut -d"x" -f3)
  #echo "  $a $b $c"
  A1=$[a*b]
  A2=$[a*c]
  A3=$[b*c]
  #echo "  $A1 $A2 $A3"
  min=$(echo "$A1 $A2 $A3" | xargs printf "%s\n" | sort -g | head -1)
  #echo "  $min"
  #echo "  $[2*(A1+A2+A3)+min]"
  sum=$[sum+2*(A1+A2+A3)+min]
done < $1
echo $sum
