#!/bin/bash

[ $# -lt 1 ] && echo "Need input" && exit 1

count=0
while read line
do
  if ! echo $line | grep "[aeiou].*[aeiou].*[aeiou]" > /dev/null; then
    continue
  elif ! echo $line | grep "\(.\)\1" > /dev/null; then
    continue
  elif echo $line | grep -E "ab|cd|pq|xy" > /dev/null; then
    continue
  fi
  count=$[count+1]
done < $1

echo $count
count=0

while read line
do
  if ! echo $line | grep  "\(..\).*\1" > /dev/null; then
    continue
  elif ! echo $line | grep "\(.\).\1" > /dev/null; then
    continue
  fi
  count=$[count+1]
done < $1

echo $count
